version: '3.3'
services:
  mysql_database:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  application:
      depends_on:
        - database
      build: ./automafia
      restart: on-failure
      env_file: ./.env
      ports:
        - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      environment:
        SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver"
#            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#            "spring.jpa.hibernate.ddl-auto" : "update"
            "spring.jackson.serialization.FAIL_ON_EMPTY_BEANS" : "false"
            "spring.jpa.properties.hibernate.enable_lazy_load_no_trans" : "true"
            "logging.level.org.springframework.web" : "DEBUG"
          }'
      volumes:
        - .m2:/root/.m2
      stdin_open: true
      tty: true
# Names our volume
volumes:
  my-db: