#  https://medium.com/@chrischuck35/how-to-create-a-mysql-instance-with-docker-compose-1598f3cc1bee
version: '3.3'
services:
  automafia_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'automafia'
      MYSQL_USER: 'automafia'
      MYSQL_PASSWORD: 'Maf99AuOt!@'
      MYSQL_ROOT_PASSWORD: 's@lMa99Pw!'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./default_game_configs.sql:/docker-entrypoint-initdb.d/1.sql
      - mafia:/var/lib/mysql
# Names our volume
volumes:
  default_game_configs:
  mafia: